import os
from selenium import webdriver
from time import sleep

from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
os.environ['PATH'] += r"C:\chromedriver-win64"
driver = webdriver.Chrome()
actions = ActionChains(driver)

def login_user():
    driver.implicitly_wait(5)
    driver.get("https://hnaya.ir/")
    driver.set_window_size(400,890)
    sleep(3)
    driver.find_element("xpath","(//p[@class='title2 pt-1 '])[3]").click()
    sleep(7)
    phone_input = driver.find_element("tag name","input")
    phone_input.click()
    sleep(1)
    phone_input.send_keys(Keys.BACKSPACE)
    phone_input.send_keys(Keys.BACKSPACE)
    sleep(2)
    phone_number= "89155608056"
    phone_input.send_keys(phone_number)
    sleep(1)
    driver.find_element("tag name","h6").click()
    sleep(1)
    driver.find_element("xpath","//h6[text()='استمر']").click()
    sleep(2)
    driver.find_element("xpath","//input[@type='tel']").send_keys("1")
    driver.find_element("xpath","(//input[@type='tel'])[2]").send_keys("1")
    driver.find_element("xpath","(//input[@type='tel'])[3]").send_keys("1")
    driver.find_element("xpath","(//input[@type='tel'])[4]").send_keys("1")
    sleep(6)
    dom = driver.page_source
    assert "یوزر تست وب 12 مهر" in dom



def login_tashakol():
    driver.implicitly_wait(5)
    driver.get("https://hnaya.ir/")
    driver.set_window_size(400,890)
    sleep(3)
    driver.find_element("xpath","(//p[@class='title2 pt-1 '])[3]").click()
    sleep(7)
    driver.find_element("xpath","//button[text()='مجموعة']").click()
    sleep(1)
    phone_input = driver.find_element("tag name","input")
    phone_input.click()
    sleep(1)
    phone_input.send_keys(Keys.BACKSPACE)
    phone_input.send_keys(Keys.BACKSPACE)
    sleep(2)
    phone_number= "89196549827"
    phone_input.send_keys(phone_number)
    sleep(1)
    driver.find_element("tag name","h6").click()
    sleep(1)
    driver.find_element("xpath","//h6[text()='استمر']").click()
    sleep(2)
    driver.find_element("xpath","//input[@type='tel']").send_keys("1")
    driver.find_element("xpath","(//input[@type='tel'])[2]").send_keys("1")
    driver.find_element("xpath","(//input[@type='tel'])[3]").send_keys("1")
    driver.find_element("xpath","(//input[@type='tel'])[4]").send_keys("1")
    sleep(6)
    dom = driver.page_source
    assert "تشکل تست وب 12 مهر" in dom


def sign_in_user():
    driver.implicitly_wait(5)
    driver.get("https://hnaya.ir/")
    driver.set_window_size(400, 890)
    sleep(3)
    driver.find_element("xpath", "(//p[@class='title2 pt-1 '])[3]").click()
    sleep(7)
    phone_input = driver.find_element("tag name", "input")
    phone_input.click()
    sleep(1)
    phone_input.send_keys(Keys.BACKSPACE)
    phone_input.send_keys(Keys.BACKSPACE)
    sleep(2)
    phone_number = "89155608056"
    phone_input.send_keys(phone_number)
    sleep(1)
    driver.find_element("tag name", "h6").click()
    sleep(1)
    driver.find_element("xpath", "//h6[text()='استمر']").click()
    sleep(2)
    driver.find_element("xpath", "//input[@type='tel']").send_keys("1")
    driver.find_element("xpath", "(//input[@type='tel'])[2]").send_keys("1")
    driver.find_element("xpath", "(//input[@type='tel'])[3]").send_keys("1")
    driver.find_element("xpath", "(//input[@type='tel'])[4]").send_keys("1")
    sleep(7)
    uname = "یوزر تست وب 12 مهر"
    driver.find_element("xpath", "//input[contains(@class,'w-full rounded-lg')]").send_keys(uname)
    driver.find_element("xpath","//h6[text()='تأييد']").click()
    sleep(5)
    dom = driver.page_source
    assert uname in dom



def sign_in_tashakol():
    driver.implicitly_wait(5)
    driver.get("https://hnaya.ir/")
    driver.set_window_size(400, 890)
    sleep(3)
    driver.find_element("xpath", "(//p[@class='title2 pt-1 '])[3]").click()
    sleep(7)
    driver.find_element("xpath","//button[text()='مجموعة']").click()
    sleep(1)
    phone_input = driver.find_element("tag name", "input")
    phone_input.click()
    sleep(1)
    phone_input.send_keys(Keys.BACKSPACE)
    phone_input.send_keys(Keys.BACKSPACE)
    sleep(2)
    phone_number = "89196549827"
    phone_input.send_keys(phone_number)
    sleep(1)
    driver.find_element("tag name", "h6").click()
    sleep(1)
    driver.find_element("xpath", "//h6[text()='استمر']").click()
    sleep(2)
    driver.find_element("xpath", "//input[@type='tel']").send_keys("1")
    driver.find_element("xpath", "(//input[@type='tel'])[2]").send_keys("1")
    driver.find_element("xpath", "(//input[@type='tel'])[3]").send_keys("1")
    driver.find_element("xpath", "(//input[@type='tel'])[4]").send_keys("1")
    sleep(7)
    uname = "تشکل تست وب 12 مهر"
    driver.find_element("xpath","//input[contains(@class,'w-full rounded-lg')]").send_keys(uname)
    driver.find_element("xpath","//h6[text()='تأييد']").click()
    sleep(5)
    dom = driver.page_source
    assert uname in dom

def create_request():
    driver.implicitly_wait(5)
    driver.get("https://hnaya.ir/")
    driver.set_window_size(400, 1050)
    sleep(3)
    driver.find_element("xpath", "(//p[@class='title2 pt-1 '])[3]").click()
    sleep(7)
    phone_input = driver.find_element("tag name", "input")
    phone_input.click()
    sleep(1)
    phone_input.send_keys(Keys.BACKSPACE)
    phone_input.send_keys(Keys.BACKSPACE)
    sleep(2)
    phone_number = "89155608056"
    phone_input.send_keys(phone_number)
    sleep(1)
    driver.find_element("tag name", "h6").click()
    sleep(1)
    driver.find_element("xpath", "//h6[text()='استمر']").click()
    sleep(3)
    driver.find_element("xpath", "(//h6[text()='حاليا لا'])").click()
    sleep(1)
    driver.find_element("xpath", "//input[@type='tel']").send_keys("1")
    driver.find_element("xpath", "(//input[@type='tel'])[2]").send_keys("1")
    driver.find_element("xpath", "(//input[@type='tel'])[3]").send_keys("1")
    driver.find_element("xpath", "(//input[@type='tel'])[4]").send_keys("1")
    sleep(5)
    driver.find_element("xpath","//a[@href='/ar/create-form']").click()
    sleep(5)
    title = "درخواست تست وب 28 شهریور"
    driver.find_element("xpath","//input[@placeholder='اكتب']").send_keys(title)
    sleep(1)
    driver.find_element("tag name","textarea").send_keys("لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ")
    sleep(1)
    driver.find_element("id","map").click()
    sleep(3)
    driver.find_element("xpath","//h6[text()='تأييد المكان المختار']").click()
    sleep(1)
    driver.find_element("xpath","//span[text()='تفاصيل أكثر']").click()
    sleep(30)
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    sleep(1)
    driver.find_element("xpath","//p[@class='text-gray4']").click()
    sleep(1)
    driver.find_element("xpath","(//input[@id='radio'])[2]").click()
    driver.find_element("xpath","(//input[@id='radio'])[4]").click()
    sleep(1)
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    driver.find_element("xpath","(//input[@id='radio'])[15]").click()
    sleep(1)
    driver.find_element("xpath","(//textarea[@placeholder='اكتب'])[2]").send_keys("موضوع تستی")
    sleep(1)
    driver.find_element("xpath","(//h6[text()='تأييد'])[2]").click()
    sleep(1)
    driver.find_element("id","requirementsList").click()
    sleep(1)
    driver.find_element("xpath","//button[contains(@class,'mb-[19px] w-[52px]')]").click()
    sleep(1)
    driver.find_element("id", "react-select-requirementSelect-placeholder").click()
    sleep(1)
    driver.find_element("xpath", "//*[text()='المالية']").click()
    sleep(1)
    driver.find_element("id", "input").send_keys("8460")
    sleep(1)
    driver.find_element("xpath", "(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath", "//button[contains(@class,'mb-[19px] w-[52px]')]").click()
    sleep(1)
    driver.find_element("xpath", "//div[text()='اختيار الاحتياجات']").click()
    sleep(1)
    driver.find_element("xpath", "//*[text()='المعنوية']").click()
    sleep(1)
    driver.find_element("xpath", "(//textarea[@rows='5'])[2]").send_keys("توضیحات معنوی")
    driver.find_element("xpath", "(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath", "//button[contains(@class,'mb-[19px] w-[52px]')]").click()
    sleep(1)
    driver.find_element("xpath", "//div[text()='اختيار الاحتياجات']").click()
    sleep(1)
    driver.find_element("xpath", "//*[text()='الفكرة']").click()
    sleep(1)
    driver.find_element("xpath", "(//textarea[@rows='5'])[2]").send_keys("توضیحات ایده")
    driver.find_element("xpath", "(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath", "//button[contains(@class,'mb-[19px] w-[52px]')]").click()
    sleep(1)
    driver.find_element("xpath", "//div[text()='اختيار الاحتياجات']").click()
    sleep(1)
    driver.find_element("xpath", "//*[text()='الحضورية']").click()
    sleep(1)
    driver.find_element("xpath", "(//textarea[@rows='5'])[2]").send_keys("توضیحات حضور")
    driver.find_element("xpath", "(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath", "//button[contains(@class,'mb-[19px] w-[52px]')]").click()
    sleep(1)
    driver.find_element("xpath", "//div[text()='اختيار الاحتياجات']").click()
    sleep(1)
    driver.find_element("xpath", "//*[text()='المساعدات']").click()
    sleep(1)
    driver.find_element("xpath", "(//textarea[@rows='5'])[2]").send_keys("توضیحات ظرفیت")
    driver.find_element("xpath", "(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath", "//button[contains(@class,'mb-[19px] w-[52px]')]").click()
    sleep(1)
    driver.find_element("xpath", "//div[text()='اختيار الاحتياجات']").click()
    sleep(1)
    driver.find_element("xpath", "//*[text()='التخصصات']").click()
    sleep(1)
    driver.find_element("xpath", "(//textarea[@rows='5'])[2]").send_keys("توضیحات تخصصی")
    driver.find_element("xpath", "(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath", "//h6[text()='تأييد']").click()
    sleep(1)
    driver.find_element("xpath", "(//input[@placeholder='اكتب'])[2]").send_keys("تیموری، خ. حبیب الله جنوبی، نرسیده به خ. آزادی، خ. حبیب زادگان.")
    sleep(1)
    driver.find_element("xpath","//input[@id='calendar']").click()
    sleep(1)
    driver.find_element("xpath","(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath","(//input[@id='calendar'])[2]").click()
    sleep(1)
    driver.find_element("xpath","(//div[text()='02'])[2]").click()
    driver.find_element("xpath","//div[text()='11']").click()
    sleep(1)
    driver.find_element("xpath","(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath","//div[contains(@class,'my-[25px] lg:mt-[35px]')]//div").click()
    sleep(1)
    driver.find_element("xpath","//label[@class='flex items-center  ']/following-sibling::input[1]").send_keys("تگ 1")
    driver.find_element("xpath","(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath","//label[@class='flex items-center  ']/following-sibling::input[1]").send_keys("تگ 2")
    driver.find_element("xpath","(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("class name","react-modal-sheet-backdrop").click()
    sleep(1)
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    driver.find_element("xpath","(//h6[text()='تأييد'])[2]").click()
    sleep(5)
    driver.find_element("xpath","//p[text()='حساب الطلب']").click()
    sleep(3)
    dom = driver.page_source
    assert title in dom




def create_project():
    driver.implicitly_wait(5)
    driver.get("https://hnaya.ir/")
    driver.set_window_size(400, 1050)
    sleep(3)
    driver.find_element("xpath", "(//p[@class='title2 pt-1 '])[3]").click()
    sleep(7)
    driver.find_element("xpath","//button[text()='مجموعة']").click()
    sleep(1)
    phone_input = driver.find_element("tag name", "input")
    phone_input.click()
    sleep(1)
    phone_input.send_keys(Keys.BACKSPACE)
    phone_input.send_keys(Keys.BACKSPACE)
    sleep(2)
    phone_number = "89196549827"
    phone_input.send_keys(phone_number)
    sleep(1)
    driver.find_element("tag name", "h6").click()
    sleep(1)
    driver.find_element("xpath", "//h6[text()='استمر']").click()
    sleep(3)
    driver.find_element("xpath", "(//h6[text()='حاليا لا'])").click()
    sleep(1)
    driver.find_element("xpath", "//input[@type='tel']").send_keys("1")
    driver.find_element("xpath", "(//input[@type='tel'])[2]").send_keys("1")
    driver.find_element("xpath", "(//input[@type='tel'])[3]").send_keys("1")
    driver.find_element("xpath", "(//input[@type='tel'])[4]").send_keys("1")
    sleep(5)
    driver.find_element("xpath","//a[@href='/ar/create-form']").click()
    sleep(5)
    title = "پروژه تست وب 12 مهر"
    driver.find_element("xpath", "//input[@placeholder='اكتب']").send_keys(title)
    sleep(1)
    driver.find_element("tag name","textarea").send_keys("لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ")
    sleep(1)
    driver.find_element("id","map").click()
    sleep(3)
    driver.find_element("xpath","//h6[text()='تأييد المكان المختار']").click()
    sleep(1)
    driver.find_element("xpath","//span[text()='تفاصيل أكثر']").click()
    sleep(30)
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    sleep(1)
    driver.find_element("xpath","//p[@class='text-gray4']").click()
    sleep(1)
    driver.find_element("xpath","(//input[@id='radio'])[2]").click()
    driver.find_element("xpath","(//input[@id='radio'])[4]").click()
    sleep(1)
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    driver.find_element("xpath","(//input[@id='radio'])[15]").click()
    sleep(1)
    driver.find_element("xpath","(//textarea[@placeholder='اكتب'])[2]").send_keys("موضوع تستی")
    sleep(1)
    driver.find_element("xpath","(//h6[text()='تأييد'])[2]").click()
    sleep(1)
    driver.find_element("xpath","(//div[contains(@class,'flex justify-between')])[3]").click()
    sleep(1)
    driver.find_element("xpath","//button[contains(@class,'mb-[19px] w-[52px]')]").click()
    sleep(1)
    # import pdb; pdb.set_trace()
    driver.find_element("xpath","//div[text()='اختيار الاحتياجات']").click()
    sleep(1)
    driver.find_element("xpath","//*[text()='المالية']").click()
    sleep(1)
    driver.find_element("id","input").send_keys("8460")
    sleep(1)
    driver.find_element("xpath","(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath","//button[contains(@class,'mb-[19px] w-[52px]')]").click()
    sleep(1)
    driver.find_element("xpath", "//div[text()='اختيار الاحتياجات']").click()
    sleep(1)
    driver.find_element("xpath", "//*[text()='المعنوية']").click()
    sleep(1)
    driver.find_element("xpath","(//textarea[@rows='5'])[2]").send_keys("توضیحات معنوی")
    driver.find_element("xpath","(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath","//button[contains(@class,'mb-[19px] w-[52px]')]").click()
    sleep(1)
    driver.find_element("xpath", "//div[text()='اختيار الاحتياجات']").click()
    sleep(1)
    driver.find_element("xpath", "//*[text()='الفكرة']").click()
    sleep(1)
    driver.find_element("xpath","(//textarea[@rows='5'])[2]").send_keys("توضیحات ایده")
    driver.find_element("xpath","(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath", "//button[contains(@class,'mb-[19px] w-[52px]')]").click()
    sleep(1)
    driver.find_element("xpath", "//div[text()='اختيار الاحتياجات']").click()
    sleep(1)
    driver.find_element("xpath", "//*[text()='الحضورية']").click()
    sleep(1)
    driver.find_element("xpath", "(//textarea[@rows='5'])[2]").send_keys("توضیحات حضور")
    driver.find_element("xpath", "(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath", "//button[contains(@class,'mb-[19px] w-[52px]')]").click()
    sleep(1)
    driver.find_element("xpath", "//div[text()='اختيار الاحتياجات']").click()
    sleep(1)
    driver.find_element("xpath", "//*[text()='المساعدات']").click()
    sleep(1)
    driver.find_element("xpath", "(//textarea[@rows='5'])[2]").send_keys("توضیحات ظرفیت")
    driver.find_element("xpath", "(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath", "//button[contains(@class,'mb-[19px] w-[52px]')]").click()
    sleep(1)
    driver.find_element("xpath", "//div[text()='اختيار الاحتياجات']").click()
    sleep(1)
    driver.find_element("xpath", "//*[text()='التخصصات']").click()
    sleep(1)
    driver.find_element("xpath", "(//textarea[@rows='5'])[2]").send_keys("توضیحات تخصصی")
    driver.find_element("xpath", "(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath","//h6[text()='تأييد']").click()
    sleep(1)
    driver.find_element("xpath","(//input[@placeholder='اكتب'])[2]").send_keys("تیموری، خ. حبیب الله جنوبی، نرسیده به خ. آزادی، خ. حبیب زادگان.")
    sleep(1)
    driver.find_element("id","calendar").click()
    sleep(1)
    driver.find_element("xpath","(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath","(//input[@id='calendar'])[2]").click()
    sleep(1)
    driver.find_element("xpath","(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath", "(//input[@id='calendar'])[3]").click()
    sleep(1)
    driver.find_element("xpath","//div[text()='10']").click()
    sleep(1)
    driver.find_element("xpath","(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("id","audience").click()
    sleep(1)
    driver.find_element("xpath","//input[@min='0']").send_keys("10")
    driver.find_element("xpath","(//input[@type='tel'])[2]").send_keys("42")
    sleep(1)
    driver.find_element("xpath", "//h6[text()='الجنس']").click()
    driver.find_element("id","3").click()
    sleep(1)
    driver.find_element("xpath","(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath","//div[contains(@class,'my-[25px] lg:mt-[35px]')]//div").click()
    sleep(1)
    driver.find_element("xpath","//label[@class='flex items-center  ']/following-sibling::input[1]").send_keys("تگ 1")
    driver.find_element("xpath","(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("xpath","//label[@class='flex items-center  ']/following-sibling::input[1]").send_keys("تگ 2")
    driver.find_element("xpath","(//h6[text()='تأييد'])[3]").click()
    sleep(1)
    driver.find_element("class name","react-modal-sheet-backdrop").click()
    sleep(1)
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    driver.find_element("xpath","(//h6[text()='تأييد'])[2]").click()
    sleep(5)
    driver.find_element("xpath","//p[text()='حساب المشروع']").click()
    sleep(2)
    dom = driver.page_source
    assert title in dom

create_request()

